name: Keep Alive Bot

on:
  schedule:
    - cron: '*/14 * * * *'  # প্রতি ১৪ মিনিট পর পর রান হবে
  workflow_dispatch:        # ম্যানুয়ালি রান করার অপশন

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render URL
        run: curl https://telegram-seo-botbackendapp-1.onrender.com